spring:
  thymeleaf:
    mode: HTML #LEGACYHTML5
    cache: false
    prefix: classpath:/templates/ #最后需要 /
    suffix: .html
    encoding: UTF-8
    check-template-location: true
  servlet:
    multipart:
      enabled: false
  profiles:
    active: beta #环境隔离
  mail:
    username: inform@islab.net.cn
    password: Alerter.2019
    default-encoding: UTF-8
    host: smtp.exmail.qq.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: hxy.dream.dao.model
  # 支持通配符 * 或者 ; 分割
  typeEnumsPackage: hxy.dream.entity.enums
  global-config:
    db-config:
      logic-delete-field: deleted  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# pagehelper分页插件
pagehelper:
  # 数据库的方言
  helperDialect: mysql
  # 启用合理化，如果pageNum < 1会查询第一页，如果pageNum > pages会查询最后一页
  reasonable: true
server:
  port: 8080
#  ssl:
#    key-store: classpath:cupbtop.jks
#    key-store-password: Sigh,0404
#    key-store-type: JKS #RSA
#    enabled: true
#    #    key-password: Sigh,0404
#    #    trust-store: classpath:cupbtop.jks
#    #    trust-store-password: Sigh,0404
#    #    trust-store-type: JKS
#    protocol: TLS
