#线上测试配置
spring:
  datasource:
    url: jdbc:mysql://mysql.cupb.top:3306/eric?useUnicode=true&serverTimezone=GMT%2b8&characterEncoding=UTF-8
    username: eric
    password: dream,1234..
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000 # 池中连接关闭后的最长生命周期 20分钟
  #    type:  com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: false
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      #eager: true
  sql:
    init:
      platform: mysql
  data:
    # redis 配置
    redis:
      # 地址  121.36.136.109  localhost
      host: 52.131.246.191
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 3
      # 密码
      password: newpass
      # 连接超时时间
      timeout: 10s
      jedis:
        pool:
          min-idle: 10
          max-idle: 20
          max-wait: -1ms
          max-active: 200
#      ssl: true

logging:
  level:
    root: info #其他的包都是使用info正常显示日志
    hxy.dream.dao: trace # 显示mybatis的操作时候所有级别的日志
    hxy.dream: debug
    com.fasterxml.jackson: debug

#server:
#  ssl:
#    key-store: classpath:cupbtop.jks
#    key-store-password: Sigh,0404
#    key-store-type: JKS #RSA
#    port: 8443