GET http://localhost:8080/user/get/1

### 添加
POST http://localhost:8080/user/add/body
Content-Type: application/json
Accept: application/json

{
  "gender": 200,
  "name": "lis1i1",
  "age": 23,
  "address": "安徽省安庆市"
}

### 添加
POST http://localhost:8080/user/add/body
Content-Type: application/json
Accept: application/json

{
  "gender": {
    "code": 200,
    "description": "女"
  },
  "name": "lis1i1",
  "age": 23
}

### 删除
DELETE http://localhost:8080/user/delete?id=2

### 添加
POST http://localhost:8080/user/add2?gender=0&name=张三&age=22
Content-Type: application/x-www-form-urlencoded
Accept: application/json


### 列表
GET http://localhost:8080/user/list


### 事务测试传播机制
GET http://localhost:8080/transaction/propagation

### 事务隔离级别测试
GET http://localhost:8080/transaction/isolation

### 事务测试
GET http://localhost:8080/

### 返回json测试
GET http://localhost:8080/exception

###
GET http://localhost:8080/exception-output


### servlet

GET localhost:8080/AsyncRunningServlet2
Content-Type: application/json

{
  "aa": "a"
}

### AsyncServlet
GET localhost:8080/AsyncServlet


### ThreadLocal 线程安全测试
GET localhost:8080/threadlocal/wrong?userId=122

### ConcurentHashMap
GET localhost:8080/concurrentHashMap/wrong

### Long精度测试
GET http://localhost:8080/long