GET http://localhost:8080/user/get/12

### 添加
POST http://localhost:8080/user/add/body
Content-Type: application/json
Accept: application/json

{
    "gender": 2,
    "name": "lis1i1",
    "age": 23
}

###
### 添加
POST http://localhost:8080/user/add2?gender=0&name=张三&age=22
Content-Type: application/x-www-form-urlencoded
Accept: application/json


### 列表
GET http://localhost:8080/user/list


### 事务测试
GET http://localhost:8080/transaction/

### 事务测试
GET http://localhost:8080/